// <auto-generated />
using System;
using IntegrationServicesProject2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationServicesProject2.Database.Migrations
{
    [DbContext(typeof(ArchiveJobsDbContext))]
    [Migration("20261008083815_CreateArchiveJobs")]
    partial class CreateArchiveJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Archive")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegrationServicesProject2.Database.Entities.ArchiveJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveOlderThanDays")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateOnly>("LastSuccesProcessedAt")
                        .HasColumnType("date");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(257)
                        .HasColumnType("nvarchar(257)");

                    b.HasKey("Id");

                    b.ToTable("ArchiveJobs", "Archive");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchiveOlderThanDays = 90,
                            DatabaseName = "MyData",
                            LastSuccesProcessedAt = new DateOnly(2026, 9, 29),
                            TableName = "MyData.Snapshots"
                        },
                        new
                        {
                            Id = 2,
                            ArchiveOlderThanDays = 30,
                            DatabaseName = "SmartHome",
                            LastSuccesProcessedAt = new DateOnly(2026, 10, 3),
                            TableName = "SmartHome.Events"
                        },
                        new
                        {
                            Id = 3,
                            ArchiveOlderThanDays = 180,
                            DatabaseName = "SalesDemo",
                            LastSuccesProcessedAt = new DateOnly(2026, 9, 15),
                            TableName = "dbo.Orders"
                        },
                        new
                        {
                            Id = 4,
                            ArchiveOlderThanDays = 60,
                            DatabaseName = "WarehouseDemo",
                            LastSuccesProcessedAt = new DateOnly(2026, 10, 1),
                            TableName = "audit.StockMovements"
                        },
                        new
                        {
                            Id = 5,
                            ArchiveOlderThanDays = 14,
                            DatabaseName = "TelemetryDemo",
                            LastSuccesProcessedAt = new DateOnly(2026, 9, 22),
                            TableName = "dbo.Readings"
                        },
                        new
                        {
                            Id = 6,
                            ArchiveOlderThanDays = 365,
                            DatabaseName = "SupportDemo",
                            LastSuccesProcessedAt = new DateOnly(2026, 8, 31),
                            TableName = "dbo.Tickets"
                        },
                        new
                        {
                            Id = 7,
                            ArchiveOlderThanDays = 120,
                            DatabaseName = "PaymentsDemo",
                            LastSuccesProcessedAt = new DateOnly(2026, 10, 5),
                            TableName = "audit.Transactions"
                        },
                        new
                        {
                            Id = 8,
                            ArchiveOlderThanDays = 7,
                            DatabaseName = "LogsDemo",
                            LastSuccesProcessedAt = new DateOnly(2026, 10, 7),
                            TableName = "dbo.ApplicationLogs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
